disabled_rules:
  - required_deinit # we usually do not have the need for this
  - explicit_acl # Because extension or class must have modifier, so its implicit
  - explicit_enum_raw_value # Because sometimes Raw Values is not needed
  - no_extension_access_modifier # Because its more readable to prefix extension than function
  - no_grouping_extension # better for readability
  - object_literal # we must choose between this and discouraged_object_literal
  - missing_docs # too heavy + code should autocomment itself
  - no_magic_numbers # too sensitive
  - discouraged_optional_collection
  - explicit_type_interface # Because sometimes its better to use type inference
  - anonymous_argument_in_multiline_closure # we like it like this
  - prefer_zero_over_explicit_init # we like it like this
  - implicit_return # Prefer implicit returns in closures, functions and getters.
  - explicit_top_level_acl # Painful
  - nesting # Does not work well with TCA, limits SwiftUI views organization through extensions
  - todo # Does not warrant a lint warning
  - raw_value_for_camel_cased_codable_enum # d'ont need
  # Styling - handled by SwiftFormat
  - attributes
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comma_inheritance
  - conditional_returns_on_newline
  - control_statement
  - direct_return
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_self
  - file_header
  - file_types_order
  - identifier_name
  - implicit_getter
  - indentation_width
  - leading_whitespace
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - non_overridable_class_declaration
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_name_whitespace
  - optional_enum_case_matching
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_self_in_closure
  - return_arrow_whitespace
  - self_binding
  - single_test_class
  - sorted_enum_cases
  - sorted_imports
  - statement_position
  - superfluous_else
  - switch_case_alignment
  - switch_case_on_newline
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return

opt_in_rules:
  - async_without_await
  - block_based_kvo
  - convenience_type
  - discouraged_assert
  - discouraged_object_literal
  - duplicate_imports
  - explicit_top_level_acl
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - generic_type_name
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_objc_type
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - local_doc_comment
  - nimble_operator
  - no_fallthrough_only
  - pattern_matching_keywords
  - prefer_nimble
  - private_over_fileprivate
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - implicit_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_value_from_void_function
  - shorthand_optional_binding
  - static_operator
  - strict_fileprivate
  - syntactic_sugar
  - toggle_bool
  - trailing_semicolon
  - type_name
  - unavailable_condition
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_synthesized_initializer
  - untyped_error_in_catch
  - unused_enumerated
  - void_function_in_ternary
  - xct_specific_matcher
  - xctfail_message
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - array_init
  - balanced_xctest_lifecycle
  - class_delegate_protocol
  - comment_spacing
  - compiler_protocol_init
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_xctest_method
  - expiring_todo
  - ibinspectable_in_extension
  - identical_operands
  - invalid_swiftlint_command
  - lower_acl_than_parent
  - mark
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - private_subject
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - required_enum_case
  - self_in_property_initialization
  - strong_iboutlet
  - superfluous_disable_command
  - test_case_accessibility
  - unhandled_throwing_task
  - unneeded_override
  - unowned_variable_capture
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_setter_value
  - valid_ibinspectable
  - weak_delegate
  - yoda_condition
  - enum_case_associated_values_count
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - type_body_length
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_boolean
  - reduce_into
  - sorted_first_last
  - cyclomatic_complexity
  - blanket_disable_command
  - discouraged_optional_boolean
  # Styling - not handled by SwiftFormat
  - inclusive_language
  - computed_accessors_order
  - shorthand_operator

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - Build

custom_rules:
  no_any_view:
    name: "No Any View"
    regex: "AnyView"
    message: "Avoid using AnyView as it can lead to performance or animation issues. Consider using generics or protocol-oriented approaches instead."
    severity: warning
  use_umbrella_to_import_tca:
    name: "Do you really want to import TCA only ?"
    regex: "import ComposableArchitecture"
    message: "Most of the time, you'll want to import SharedCommonArchitecture which encapsulate TCA and Helpers at once."
    severity: warning
  use_dependency_for_date:
    name: "Use Dependency Injection for Date"
    regex: "Calendar\\.current|Date\\(\\)"
    message: "Use Dependency Injection to get the current date or calendar instance instead of directly accessing Calendar.current or creating a new Date instance."
    severity: error
  use_dependency_for_uuid:
    name: "Use Dependency Injection for UUID"
    regex: "UUID\\.uuidString|UUID\\(\\)"
    message: "Use Dependency Injection to get UUID instances instead of directly accessing UUID.uuidString or creating a new UUID instance."
    severity: error
  tca_break_down_runs:
    name: "Break down TCA run effects"
    regex: "send\\(\\.[a-zA-Z]+\\(await"
    message: "Break down TCA run effects to improve compiler performance. Consider separating the send action from the await call."
    severity: warning
  onappear_must_be_last:
    name: "onAppear should be the outermost modifier"
    regex: "\\.onAppear\\s*\\{[^}]*\\}\\s*\\."
    message: "Place .onAppear as the last modifier in the chain to prevent it from being called multiple times. Lifecycle modifiers should be outermost."
    severity: warning
  ondisappear_must_be_last:
    name: "onDisappear should be the outermost modifier"
    regex: "\\.onDisappear\\s*\\{[^}]*\\}\\s*\\."
    message: "Place .onDisappear as the last modifier in the chain to prevent it from being called multiple times. Lifecycle modifiers should be outermost."
    severity: warning
  task_must_be_last:
    name: "task should be the outermost modifier"
    regex: "\\.task\\s*\\{[^}]*\\}\\s*\\."
    message: "Place .task as the last modifier in the chain to prevent it from being called multiple times. Lifecycle modifiers should be outermost."
    severity: warning
  onchange_must_be_last:
    name: "onChange should be the outermost modifier"
    regex: "\\.onChange\\(of:[^)]*\\)\\s*\\{[^}]*\\}\\s*\\."
    message: "Place .onChange as the last modifier in the chain to prevent it from being called multiple times. Observation modifiers should be outermost."
    severity: warning
  onreceive_must_be_last:
    name: "onReceive should be the outermost modifier"
    regex: "\\.onReceive\\([^)]*\\)\\s*\\{[^}]*\\}\\s*\\."
    message: "Place .onReceive as the last modifier in the chain to prevent it from being called multiple times. Observation modifiers should be outermost."
    severity: warning

analyzer_rules:
  - unused_declaration
  - typesafe_array_init
  - capture_variable

line_length:
  warning: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

shorthand_operator:
  severity: warning

weak_delegate:
  severity: error

type_name:
  allowed_symbols: "_"

empty_count:
  severity: error

unhandled_throwing_task:
  severity: error

force_cast:
  severity: error

file_length:
  ignore_comment_only_lines: true

trailing_whitespace:
  ignores_empty_lines: true

cyclomatic_complexity:
  ignores_case_statements: true

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
